kind: pipeline
type: docker
name: integration

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk
    environment:
      CONNECTION_STRING:
        from_secret: MyConnectionString
    commands:
      - dotnet build  
    
  - name: test
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
     - dotnet test
       
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    environment:
      SONARSECRET:
        from_secret: SonarCubeSecret
      commands:
        - dotnet sonarscanner begin 
          /k:"$easv-devops_NewCalculator"
          /d:sonar.host.url="http://sonar.setgo.dk:9000"   
          /d:sonar.token="$SONARSECRET"
        - dotnet build --no-incremental
        - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xlm"
        - dotnet sonarscanner end /d:sonar.token="$SONARSCRET"